# -*- encoding: utf-8 -*-

=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

$:.push File.expand_path("../lib", __FILE__)
require "osuny_api/version"

Gem::Specification.new do |s|
  s.name        = "osuny_api"
  s.version     = OsunyApi::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Arnaud Levy", "Sébastien Gaya"]
  s.email       = ["contact@arnaudlevy.com", "sebastien.gaya@gmail.com"]
  s.homepage    = "https://www.github.com/osunyorg/api"
  s.summary     = "Osuny Ruby Gem"
  s.description = "Ruby Gem for the Osuny API"
  s.license     = 'MIT'
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
