=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.77
=end

require 'spec_helper'
require 'json'

# Unit tests for OsunyApi::CommunicationWebsitePostCategoryApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CommunicationWebsitePostCategoryApi' do
  before do
    # run before each test
    @instance = OsunyApi::CommunicationWebsitePostCategoryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommunicationWebsitePostCategoryApi' do
    it 'should create an instance of CommunicationWebsitePostCategoryApi' do
      expect(@instance).to be_instance_of(OsunyApi::CommunicationWebsitePostCategoryApi)
    end
  end

  # unit tests for communication_websites_website_id_posts_categories_get
  # Lists a website&#x27;s post categories
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_num Page number
  # @option opts [Integer] :per_page Number of items per page
  # @return [Array<CommunicationWebsitePostCategory>]
  describe 'communication_websites_website_id_posts_categories_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_posts_categories_id_delete
  # Deletes a post category
  # @param website_id Website identifier
  # @param id Category identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'communication_websites_website_id_posts_categories_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_posts_categories_id_get
  # Shows a post category
  # @param website_id Website identifier
  # @param id Category identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'communication_websites_website_id_posts_categories_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_posts_categories_id_patch
  # Updates a post category
  # @param website_id Website identifier
  # @param id Category identifier
  # @param [Hash] opts the optional parameters
  # @option opts [CategoriesIdBody3] :body 
  # @return [nil]
  describe 'communication_websites_website_id_posts_categories_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_posts_categories_post
  # Creates a post category
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [PostsCategoriesBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_posts_categories_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_posts_categories_upsert_post
  # Upsert post categories
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [CategoriesUpsertBody3] :body 
  # @return [nil]
  describe 'communication_websites_website_id_posts_categories_upsert_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
