=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'

# Unit tests for OsunyApi::CommunicationWebsitePostApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CommunicationWebsitePostApi' do
  before do
    # run before each test
    @instance = OsunyApi::CommunicationWebsitePostApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommunicationWebsitePostApi' do
    it 'should create an instance of CommunicationWebsitePostApi' do
      expect(@instance).to be_instance_of(OsunyApi::CommunicationWebsitePostApi)
    end
  end

  # unit tests for communication_websites_website_id_posts_get
  # Lists a website&#x27;s posts
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @return [Array<CommunicationWebsitePost>]
  describe 'communication_websites_website_id_posts_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_posts_id_delete
  # Deletes a post
  # @param website_id Website identifier
  # @param id Post identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'communication_websites_website_id_posts_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_posts_id_get
  # Shows a post
  # @param website_id Website identifier
  # @param id Post identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'communication_websites_website_id_posts_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_posts_id_patch
  # Updates a post
  # @param website_id Website identifier
  # @param id Post identifier
  # @param [Hash] opts the optional parameters
  # @option opts [PostsIdBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_posts_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_posts_post
  # Creates a post
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [WebsiteIdPostsBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_posts_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_posts_upsert_post
  # Upsert posts
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [PostsUpsertBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_posts_upsert_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
