=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'

# Unit tests for OsunyApi::CommunicationWebsiteAgendaCategoryApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CommunicationWebsiteAgendaCategoryApi' do
  before do
    # run before each test
    @instance = OsunyApi::CommunicationWebsiteAgendaCategoryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommunicationWebsiteAgendaCategoryApi' do
    it 'should create an instance of CommunicationWebsiteAgendaCategoryApi' do
      expect(@instance).to be_instance_of(OsunyApi::CommunicationWebsiteAgendaCategoryApi)
    end
  end

  # unit tests for communication_websites_website_id_agenda_categories_get
  # Lists a website&#x27;s agenda categories
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @return [Array<CommunicationWebsiteAgendaCategory>]
  describe 'communication_websites_website_id_agenda_categories_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_agenda_categories_id_delete
  # Deletes an agenda category
  # @param website_id Website identifier
  # @param id Category identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'communication_websites_website_id_agenda_categories_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_agenda_categories_id_get
  # Shows an agenda category
  # @param website_id Website identifier
  # @param id Category identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'communication_websites_website_id_agenda_categories_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_agenda_categories_id_patch
  # Updates an agenda category
  # @param website_id Website identifier
  # @param id Category identifier
  # @param [Hash] opts the optional parameters
  # @option opts [CategoriesIdBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_agenda_categories_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_agenda_categories_post
  # Creates an agenda category
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [AgendaCategoriesBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_agenda_categories_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_agenda_categories_upsert_post
  # Upsert agenda categories
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [CategoriesUpsertBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_agenda_categories_upsert_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
