=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'

# Unit tests for OsunyApi::CommunicationWebsitePageApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CommunicationWebsitePageApi' do
  before do
    # run before each test
    @instance = OsunyApi::CommunicationWebsitePageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommunicationWebsitePageApi' do
    it 'should create an instance of CommunicationWebsitePageApi' do
      expect(@instance).to be_instance_of(OsunyApi::CommunicationWebsitePageApi)
    end
  end

  # unit tests for communication_websites_website_id_pages_get
  # Lists a website&#x27;s pages
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @return [Array<CommunicationWebsitePage>]
  describe 'communication_websites_website_id_pages_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_pages_id_delete
  # Deletes a page
  # @param website_id Website identifier
  # @param id Page identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'communication_websites_website_id_pages_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_pages_id_get
  # Shows a page
  # @param website_id Website identifier
  # @param id Page identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'communication_websites_website_id_pages_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_pages_id_patch
  # Updates a page
  # @param website_id Website identifier
  # @param id Page identifier
  # @param [Hash] opts the optional parameters
  # @option opts [PagesIdBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_pages_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_pages_post
  # Creates a page
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [WebsiteIdPagesBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_pages_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_pages_upsert_post
  # Upsert pages
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [PagesUpsertBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_pages_upsert_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
