=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'

# Unit tests for OsunyApi::CommunicationWebsitePageCategoryApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CommunicationWebsitePageCategoryApi' do
  before do
    # run before each test
    @instance = OsunyApi::CommunicationWebsitePageCategoryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommunicationWebsitePageCategoryApi' do
    it 'should create an instance of CommunicationWebsitePageCategoryApi' do
      expect(@instance).to be_instance_of(OsunyApi::CommunicationWebsitePageCategoryApi)
    end
  end

  # unit tests for communication_websites_website_id_pages_categories_get
  # Lists a website&#x27;s page categories
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @return [Array<CommunicationWebsitePageCategory>]
  describe 'communication_websites_website_id_pages_categories_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_pages_categories_id_delete
  # Deletes a page category
  # @param website_id Website identifier
  # @param id Category identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'communication_websites_website_id_pages_categories_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_pages_categories_id_get
  # Shows a page category
  # @param website_id Website identifier
  # @param id Category identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'communication_websites_website_id_pages_categories_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_pages_categories_id_patch
  # Updates a page category
  # @param website_id Website identifier
  # @param id Category identifier
  # @param [Hash] opts the optional parameters
  # @option opts [CategoriesIdBody1] :body 
  # @return [nil]
  describe 'communication_websites_website_id_pages_categories_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_pages_categories_post
  # Creates a page category
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [PagesCategoriesBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_pages_categories_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_pages_categories_upsert_post
  # Upsert page categories
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [CategoriesUpsertBody1] :body 
  # @return [nil]
  describe 'communication_websites_website_id_pages_categories_upsert_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
