=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.77
=end

require 'spec_helper'
require 'json'

# Unit tests for OsunyApi::CommunicationWebsitePortfolioCategoryApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CommunicationWebsitePortfolioCategoryApi' do
  before do
    # run before each test
    @instance = OsunyApi::CommunicationWebsitePortfolioCategoryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommunicationWebsitePortfolioCategoryApi' do
    it 'should create an instance of CommunicationWebsitePortfolioCategoryApi' do
      expect(@instance).to be_instance_of(OsunyApi::CommunicationWebsitePortfolioCategoryApi)
    end
  end

  # unit tests for communication_websites_website_id_portfolio_categories_get
  # Lists a website&#x27;s portfolio categories
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_num Page number
  # @option opts [Integer] :per_page Number of items per page
  # @return [Array<CommunicationWebsitePortfolioCategory>]
  describe 'communication_websites_website_id_portfolio_categories_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_portfolio_categories_id_delete
  # Deletes a portfolio category
  # @param website_id Website identifier
  # @param id Category identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'communication_websites_website_id_portfolio_categories_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_portfolio_categories_id_get
  # Shows a portfolio category
  # @param website_id Website identifier
  # @param id Category identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'communication_websites_website_id_portfolio_categories_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_portfolio_categories_id_patch
  # Updates a portfolio category
  # @param website_id Website identifier
  # @param id Category identifier
  # @param [Hash] opts the optional parameters
  # @option opts [CategoriesIdBody2] :body 
  # @return [nil]
  describe 'communication_websites_website_id_portfolio_categories_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_portfolio_categories_post
  # Creates a portfolio category
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [PortfolioCategoriesBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_portfolio_categories_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_portfolio_categories_upsert_post
  # Upsert portfolio categories
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [CategoriesUpsertBody2] :body 
  # @return [nil]
  describe 'communication_websites_website_id_portfolio_categories_upsert_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
