=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.77
=end

require 'spec_helper'
require 'json'

# Unit tests for OsunyApi::CommunicationWebsiteMediaApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CommunicationWebsiteMediaApi' do
  before do
    # run before each test
    @instance = OsunyApi::CommunicationWebsiteMediaApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommunicationWebsiteMediaApi' do
    it 'should create an instance of CommunicationWebsiteMediaApi' do
      expect(@instance).to be_instance_of(OsunyApi::CommunicationWebsiteMediaApi)
    end
  end

  # unit tests for communication_medias_post
  # Create a media
  # @param [Hash] opts the optional parameters
  # @option opts [String] :url 
  # @option opts [String] :file 
  # @return [nil]
  describe 'communication_medias_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
