=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'

# Unit tests for OsunyApi::CommunicationWebsiteAgendaEventApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CommunicationWebsiteAgendaEventApi' do
  before do
    # run before each test
    @instance = OsunyApi::CommunicationWebsiteAgendaEventApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommunicationWebsiteAgendaEventApi' do
    it 'should create an instance of CommunicationWebsiteAgendaEventApi' do
      expect(@instance).to be_instance_of(OsunyApi::CommunicationWebsiteAgendaEventApi)
    end
  end

  # unit tests for communication_websites_website_id_agenda_events_get
  # Lists a website&#x27;s events
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @return [Array<CommunicationWebsiteAgendaEvent>]
  describe 'communication_websites_website_id_agenda_events_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_agenda_events_id_delete
  # Deletes an event
  # @param website_id Website identifier
  # @param id Event identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'communication_websites_website_id_agenda_events_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_agenda_events_id_get
  # Shows an event
  # @param website_id Website identifier
  # @param id Event identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'communication_websites_website_id_agenda_events_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_agenda_events_id_patch
  # Updates an event
  # @param website_id Website identifier
  # @param id Event identifier
  # @param [Hash] opts the optional parameters
  # @option opts [EventsIdBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_agenda_events_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_agenda_events_post
  # Creates an event
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [AgendaEventsBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_agenda_events_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_agenda_events_upsert_post
  # Upsert events
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [EventsUpsertBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_agenda_events_upsert_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
