=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'

# Unit tests for OsunyApi::CommunicationWebsiteApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CommunicationWebsiteApi' do
  before do
    # run before each test
    @instance = OsunyApi::CommunicationWebsiteApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommunicationWebsiteApi' do
    it 'should create an instance of CommunicationWebsiteApi' do
      expect(@instance).to be_instance_of(OsunyApi::CommunicationWebsiteApi)
    end
  end

  # unit tests for communication_websites_get
  # Lists the websites
  # @param [Hash] opts the optional parameters
  # @return [Array<CommunicationWebsite>]
  describe 'communication_websites_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_id_get
  # Shows a website
  # @param id Website identifier
  # @param [Hash] opts the optional parameters
  # @return [CommunicationWebsite]
  describe 'communication_websites_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
