=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.77
=end

require 'spec_helper'
require 'json'

# Unit tests for OsunyApi::CommunicationWebsitePortfolioProjectApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CommunicationWebsitePortfolioProjectApi' do
  before do
    # run before each test
    @instance = OsunyApi::CommunicationWebsitePortfolioProjectApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommunicationWebsitePortfolioProjectApi' do
    it 'should create an instance of CommunicationWebsitePortfolioProjectApi' do
      expect(@instance).to be_instance_of(OsunyApi::CommunicationWebsitePortfolioProjectApi)
    end
  end

  # unit tests for communication_websites_website_id_portfolio_projects_get
  # Lists a website&#x27;s projects
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_num Page number
  # @option opts [Integer] :per_page Number of items per page
  # @return [Array<CommunicationWebsitePortfolioProject>]
  describe 'communication_websites_website_id_portfolio_projects_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_portfolio_projects_id_delete
  # Deletes a project
  # @param website_id Website identifier
  # @param id Project identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'communication_websites_website_id_portfolio_projects_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_portfolio_projects_id_get
  # Shows a project
  # @param website_id Website identifier
  # @param id Project identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'communication_websites_website_id_portfolio_projects_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_portfolio_projects_id_patch
  # Updates a project
  # @param website_id Website identifier
  # @param id Project identifier
  # @param [Hash] opts the optional parameters
  # @option opts [ProjectsIdBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_portfolio_projects_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_portfolio_projects_post
  # Creates a project
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [PortfolioProjectsBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_portfolio_projects_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for communication_websites_website_id_portfolio_projects_upsert_post
  # Upsert projects
  # @param website_id Website identifier
  # @param [Hash] opts the optional parameters
  # @option opts [ProjectsUpsertBody] :body 
  # @return [nil]
  describe 'communication_websites_website_id_portfolio_projects_upsert_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
