=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'

# Unit tests for OsunyApi::UniversityOrganizationCategoryApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UniversityOrganizationCategoryApi' do
  before do
    # run before each test
    @instance = OsunyApi::UniversityOrganizationCategoryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UniversityOrganizationCategoryApi' do
    it 'should create an instance of UniversityOrganizationCategoryApi' do
      expect(@instance).to be_instance_of(OsunyApi::UniversityOrganizationCategoryApi)
    end
  end

  # unit tests for university_organizations_categories_get
  # Lists organization categories
  # @param [Hash] opts the optional parameters
  # @return [Array<UniversityOrganizationCategory>]
  describe 'university_organizations_categories_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for university_organizations_categories_id_delete
  # Deletes a organization category
  # @param id Category identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'university_organizations_categories_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for university_organizations_categories_id_get
  # Shows a organization category
  # @param id Category identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'university_organizations_categories_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for university_organizations_categories_id_patch
  # Updates a organization category
  # @param id Category identifier
  # @param [Hash] opts the optional parameters
  # @option opts [CategoriesIdBody2] :body 
  # @return [nil]
  describe 'university_organizations_categories_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for university_organizations_categories_post
  # Creates a organization category
  # @param [Hash] opts the optional parameters
  # @option opts [OrganizationsCategoriesBody] :body 
  # @return [nil]
  describe 'university_organizations_categories_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for university_organizations_categories_upsert_post
  # Upsert organization categories
  # @param [Hash] opts the optional parameters
  # @option opts [CategoriesUpsertBody2] :body 
  # @return [nil]
  describe 'university_organizations_categories_upsert_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
