=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.77
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OsunyApi::CategoriesIdBody3
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CategoriesIdBody3' do
  before do
    # run before each test
    @instance = OsunyApi::CategoriesIdBody3.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CategoriesIdBody3' do
    it 'should create an instance of CategoriesIdBody3' do
      expect(@instance).to be_instance_of(OsunyApi::CategoriesIdBody3)
    end
  end
  describe 'test attribute "category"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
