=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OsunyApi::CommunicationWebsiteAgendaEventLocalizationAddToCalendarUrls
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CommunicationWebsiteAgendaEventLocalizationAddToCalendarUrls' do
  before do
    # run before each test
    @instance = OsunyApi::CommunicationWebsiteAgendaEventLocalizationAddToCalendarUrls.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommunicationWebsiteAgendaEventLocalizationAddToCalendarUrls' do
    it 'should create an instance of CommunicationWebsiteAgendaEventLocalizationAddToCalendarUrls' do
      expect(@instance).to be_instance_of(OsunyApi::CommunicationWebsiteAgendaEventLocalizationAddToCalendarUrls)
    end
  end
  describe 'test attribute "google"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "yahoo"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "office"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "outlook"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "ical"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
