=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OsunyApi::CommunicationBlockLicenseData
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CommunicationBlockLicenseData' do
  before do
    # run before each test
    @instance = OsunyApi::CommunicationBlockLicenseData.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommunicationBlockLicenseData' do
    it 'should create an instance of CommunicationBlockLicenseData' do
      expect(@instance).to be_instance_of(OsunyApi::CommunicationBlockLicenseData)
    end
  end
  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["creative_commons"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "creative_commons_attribution"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["false", "true"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.creative_commons_attribution = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "creative_commons_commercial_use"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["true", "false"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.creative_commons_commercial_use = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "creative_commons_derivatives"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["true", "false"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.creative_commons_derivatives = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "creative_commons_sharing"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["true", "false"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.creative_commons_sharing = value }.not_to raise_error
      # end
    end
  end

end
