=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.77
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OsunyApi::OneOfcommunicationWebsitePortfolioCategoryLocalizationBlocksItems
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OneOfcommunicationWebsitePortfolioCategoryLocalizationBlocksItems' do
  before do
    # run before each test
    @instance = OsunyApi::OneOfcommunicationWebsitePortfolioCategoryLocalizationBlocksItems.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OneOfcommunicationWebsitePortfolioCategoryLocalizationBlocksItems' do
    it 'should create an instance of OneOfcommunicationWebsitePortfolioCategoryLocalizationBlocksItems' do
      expect(@instance).to be_instance_of(OsunyApi::OneOfcommunicationWebsitePortfolioCategoryLocalizationBlocksItems)
    end
  end
end
