=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OsunyApi::PagesUpsertBody
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PagesUpsertBody' do
  before do
    # run before each test
    @instance = OsunyApi::PagesUpsertBody.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PagesUpsertBody' do
    it 'should create an instance of PagesUpsertBody' do
      expect(@instance).to be_instance_of(OsunyApi::PagesUpsertBody)
    end
  end
  describe 'test attribute "pages"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
