=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

# Common files
require 'osuny_api/api_client'
require 'osuny_api/api_error'
require 'osuny_api/version'
require 'osuny_api/configuration'

# Models
require 'osuny_api/models/agenda_categories_body'
require 'osuny_api/models/agenda_events_body'
require 'osuny_api/models/categories_id_body'
require 'osuny_api/models/categories_id_body_1'
require 'osuny_api/models/categories_id_body_2'
require 'osuny_api/models/categories_upsert_body'
require 'osuny_api/models/categories_upsert_body_1'
require 'osuny_api/models/categories_upsert_body_2'
require 'osuny_api/models/communication_block_agenda'
require 'osuny_api/models/communication_block_agenda_data'
require 'osuny_api/models/communication_block_agenda_data_elements'
require 'osuny_api/models/communication_block_call_to_action'
require 'osuny_api/models/communication_block_call_to_action_data'
require 'osuny_api/models/communication_block_call_to_action_data_elements'
require 'osuny_api/models/communication_block_call_to_action_data_image'
require 'osuny_api/models/communication_block_categories'
require 'osuny_api/models/communication_block_categories_data'
require 'osuny_api/models/communication_block_chapter'
require 'osuny_api/models/communication_block_chapter_data'
require 'osuny_api/models/communication_block_contact'
require 'osuny_api/models/communication_block_contact_data'
require 'osuny_api/models/communication_block_contact_data_elements'
require 'osuny_api/models/communication_block_contact_data_time_slot_morning'
require 'osuny_api/models/communication_block_datatable'
require 'osuny_api/models/communication_block_datatable_data'
require 'osuny_api/models/communication_block_datatable_data_elements'
require 'osuny_api/models/communication_block_definitions'
require 'osuny_api/models/communication_block_definitions_data'
require 'osuny_api/models/communication_block_definitions_data_elements'
require 'osuny_api/models/communication_block_embed'
require 'osuny_api/models/communication_block_embed_data'
require 'osuny_api/models/communication_block_features'
require 'osuny_api/models/communication_block_features_data'
require 'osuny_api/models/communication_block_features_data_elements'
require 'osuny_api/models/communication_block_files'
require 'osuny_api/models/communication_block_files_data'
require 'osuny_api/models/communication_block_files_data_elements'
require 'osuny_api/models/communication_block_gallery'
require 'osuny_api/models/communication_block_gallery_data'
require 'osuny_api/models/communication_block_gallery_data_elements'
require 'osuny_api/models/communication_block_image'
require 'osuny_api/models/communication_block_image_data'
require 'osuny_api/models/communication_block_key_figures'
require 'osuny_api/models/communication_block_key_figures_data'
require 'osuny_api/models/communication_block_key_figures_data_elements'
require 'osuny_api/models/communication_block_license'
require 'osuny_api/models/communication_block_license_data'
require 'osuny_api/models/communication_block_links'
require 'osuny_api/models/communication_block_links_data'
require 'osuny_api/models/communication_block_links_data_elements'
require 'osuny_api/models/communication_block_locations'
require 'osuny_api/models/communication_block_locations_data'
require 'osuny_api/models/communication_block_locations_data_elements'
require 'osuny_api/models/communication_block_organizations'
require 'osuny_api/models/communication_block_organizations_data'
require 'osuny_api/models/communication_block_organizations_data_elements'
require 'osuny_api/models/communication_block_pages'
require 'osuny_api/models/communication_block_pages_data'
require 'osuny_api/models/communication_block_papers'
require 'osuny_api/models/communication_block_papers_data'
require 'osuny_api/models/communication_block_persons'
require 'osuny_api/models/communication_block_persons_data'
require 'osuny_api/models/communication_block_persons_data_elements'
require 'osuny_api/models/communication_block_posts'
require 'osuny_api/models/communication_block_posts_data'
require 'osuny_api/models/communication_block_programs'
require 'osuny_api/models/communication_block_programs_data'
require 'osuny_api/models/communication_block_projects'
require 'osuny_api/models/communication_block_projects_data'
require 'osuny_api/models/communication_block_sound'
require 'osuny_api/models/communication_block_sound_data'
require 'osuny_api/models/communication_block_testimonials'
require 'osuny_api/models/communication_block_testimonials_data'
require 'osuny_api/models/communication_block_testimonials_data_elements'
require 'osuny_api/models/communication_block_timeline'
require 'osuny_api/models/communication_block_timeline_data'
require 'osuny_api/models/communication_block_timeline_data_elements'
require 'osuny_api/models/communication_block_title'
require 'osuny_api/models/communication_block_title_data'
require 'osuny_api/models/communication_block_video'
require 'osuny_api/models/communication_block_video_data'
require 'osuny_api/models/communication_block_volumes'
require 'osuny_api/models/communication_website'
require 'osuny_api/models/communication_website_agenda_category'
require 'osuny_api/models/communication_website_agenda_category_localization'
require 'osuny_api/models/communication_website_agenda_category_localization_featured_image'
require 'osuny_api/models/communication_website_agenda_event'
require 'osuny_api/models/communication_website_agenda_event_localization'
require 'osuny_api/models/communication_website_agenda_event_localization_add_to_calendar_urls'
require 'osuny_api/models/communication_website_agenda_event_time_slot'
require 'osuny_api/models/communication_website_agenda_event_time_slot_localization'
require 'osuny_api/models/communication_website_deuxfleurs'
require 'osuny_api/models/communication_website_features'
require 'osuny_api/models/communication_website_git'
require 'osuny_api/models/communication_website_localization'
require 'osuny_api/models/communication_website_page'
require 'osuny_api/models/communication_website_page_category'
require 'osuny_api/models/communication_website_page_category_localization'
require 'osuny_api/models/communication_website_page_localization'
require 'osuny_api/models/communication_website_post'
require 'osuny_api/models/communication_website_post_localization'
require 'osuny_api/models/communication_website_showcase'
require 'osuny_api/models/communication_website_showcase_tags'
require 'osuny_api/models/events_id_body'
require 'osuny_api/models/events_upsert_body'
require 'osuny_api/models/one_ofcommunication_website_agenda_category_localization_blocks_items'
require 'osuny_api/models/one_ofcommunication_website_agenda_event_localization_blocks_items'
require 'osuny_api/models/one_ofcommunication_website_page_category_localization_blocks_items'
require 'osuny_api/models/one_ofcommunication_website_page_localization_blocks_items'
require 'osuny_api/models/one_ofcommunication_website_post_localization_blocks_items'
require 'osuny_api/models/one_ofuniversity_organization_category_localization_blocks_items'
require 'osuny_api/models/one_ofuniversity_organization_localization_blocks_items'
require 'osuny_api/models/organizations_categories_body'
require 'osuny_api/models/organizations_id_body'
require 'osuny_api/models/organizations_upsert_body'
require 'osuny_api/models/pages_categories_body'
require 'osuny_api/models/pages_id_body'
require 'osuny_api/models/pages_upsert_body'
require 'osuny_api/models/posts_id_body'
require 'osuny_api/models/posts_upsert_body'
require 'osuny_api/models/university_organization'
require 'osuny_api/models/university_organization_category'
require 'osuny_api/models/university_organization_category_localization'
require 'osuny_api/models/university_organization_localization'
require 'osuny_api/models/university_organizations_body'
require 'osuny_api/models/website_id_pages_body'
require 'osuny_api/models/website_id_posts_body'

# APIs
require 'osuny_api/api/communication_website_api'
require 'osuny_api/api/communication_website_agenda_category_api'
require 'osuny_api/api/communication_website_agenda_event_api'
require 'osuny_api/api/communication_website_page_api'
require 'osuny_api/api/communication_website_page_category_api'
require 'osuny_api/api/communication_website_post_api'
require 'osuny_api/api/university_organization_api'
require 'osuny_api/api/university_organization_category_api'

module OsunyApi
  class << self
    # Customize default settings for the SDK using block.
    #   OsunyApi.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
