=begin
#Osuny

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

module OsunyApi
  class CommunicationWebsiteApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Lists the websites
    # @param [Hash] opts the optional parameters
    # @return [Array<CommunicationWebsite>]
    def communication_websites_get(opts = {})
      data, _status_code, _headers = communication_websites_get_with_http_info(opts)
      data
    end

    # Lists the websites
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<CommunicationWebsite>, Integer, Hash)>] Array<CommunicationWebsite> data, response status code and response headers
    def communication_websites_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CommunicationWebsiteApi.communication_websites_get ...'
      end
      # resource path
      local_var_path = '/communication/websites'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:body] 

      return_type = opts[:return_type] || 'Array<CommunicationWebsite>' 

      auth_names = opts[:auth_names] || ['api_key']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type)

      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CommunicationWebsiteApi#communication_websites_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
    # Shows a website
    # @param id Website identifier
    # @param [Hash] opts the optional parameters
    # @return [CommunicationWebsite]
    def communication_websites_id_get(id, opts = {})
      data, _status_code, _headers = communication_websites_id_get_with_http_info(id, opts)
      data
    end

    # Shows a website
    # @param id Website identifier
    # @param [Hash] opts the optional parameters
    # @return [Array<(CommunicationWebsite, Integer, Hash)>] CommunicationWebsite data, response status code and response headers
    def communication_websites_id_get_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CommunicationWebsiteApi.communication_websites_id_get ...'
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling CommunicationWebsiteApi.communication_websites_id_get"
      end
      # resource path
      local_var_path = '/communication/websites/{id}'.sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:body] 

      return_type = opts[:return_type] || 'CommunicationWebsite' 

      auth_names = opts[:auth_names] || ['api_key']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type)

      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CommunicationWebsiteApi#communication_websites_id_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
